// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package entity

type ASNItem struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Nip           string  `json:"nip"`
	CurrentGrade  string  `json:"current_grade"`
	CurrentPlaces OPDItem `json:"current_places"`
}

type AddressItem struct {
	ID       string `json:"id"`
	Roadname string `json:"roadname"`
	Number   string `json:"number"`
	City     string `json:"city"`
	Province string `json:"province"`
}

type CategoryItem struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type LocationItem struct {
	ID      string      `json:"id"`
	Name    string      `json:"name"`
	Address AddressItem `json:"address"`
}

type OPDItem struct {
	ID      string      `json:"id"`
	Name    string      `json:"name"`
	Address AddressItem `json:"address"`
}

type OrganizerItem struct {
	ID       string       `json:"id"`
	Name     string       `json:"name"`
	Longname string       `json:"longname"`
	Location LocationItem `json:"location"`
}

type ParticipantItem struct {
	ID  string  `json:"id"`
	Asn ASNItem `json:"asn"`
}

type ScheduleItem struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	Start       string `json:"start"`
	Finish      string `json:"finish"`
}

type TrainingItem struct {
	ID           string            `json:"id"`
	Name         string            `json:"name"`
	Description  string            `json:"description"`
	Heldat       ScheduleItem      `json:"heldat"`
	Organizer    OrganizerItem     `json:"organizer"`
	Participants []ParticipantItem `json:"participants"`
}
