// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	time "time"
)

type ASN struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Nip           string `json:"nip"`
	CurrentGrade  string `json:"current_grade"`
	CurrentPlaces OPD    `json:"current_places"`
}

type ASNInput struct {
	Name string `json:"name"`
}

type Address struct {
	ID       string `json:"id"`
	Roadname string `json:"roadname"`
	Number   string `json:"number"`
	City     string `json:"city"`
	Province string `json:"province"`
}

type AddressInput struct {
	Roadname string `json:"roadname"`
	Number   string `json:"number"`
	City     string `json:"city"`
	Province string `json:"province"`
}

type Category struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Location struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Address Address `json:"address"`
}

type LocationInput struct {
	Name string `json:"name"`
}

type OPD struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Address Address `json:"address"`
}

type Organizer struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Longname string   `json:"longname"`
	Location Location `json:"location"`
}

type OrganizerInput struct {
	Name     string `json:"name"`
	Longname string `json:"longname"`
}

type Participant struct {
	ID  string `json:"id"`
	Asn ASN    `json:"asn"`
}

type Schedule struct {
	ID          string    `json:"id"`
	Description string    `json:"description"`
	Start       time.Time `json:"start"`
	Finish      time.Time `json:"finish"`
}

type ScheduleInput struct {
	Description string    `json:"description"`
	Start       time.Time `json:"start"`
	Finish      time.Time `json:"finish"`
}

type Training struct {
	ID           string        `json:"id"`
	Name         string        `json:"name"`
	Description  string        `json:"description"`
	HeldAt       Schedule      `json:"heldAt"`
	Organizer    Organizer     `json:"organizer"`
	Participants []Participant `json:"participants"`
}

type TrainingInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}
