// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	models "github.com/blackshirt/trening/models"
)

type Trx struct {
	ID          *int     `json:"id"`
	Name        *string  `json:"name"`
	Description *string  `json:"description"`
	Category    *TrxCat  `json:"category"`
	Type        *TrxType `json:"type"`
}

type TrxCat struct {
	ID          *int    `json:"id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
}

type TrxHistory struct {
	TrxID        *int          `json:"trxId"`
	Start        *string       `json:"start"`
	Finish       *string       `json:"finish"`
	Organizer    *models.Org   `json:"organizer"`
	Location     *models.Org   `json:"location"`
	Participants []*models.Asn `json:"participants"`
}

type TrxInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type TrxType struct {
	ID          *int    `json:"id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
}

type TrxTypeInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type TrxCatInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}
