// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	time "time"
)

type AddressInput struct {
	Name     string `json:"name"`
	Roadname string `json:"roadname"`
	Number   string `json:"number"`
	City     string `json:"city"`
	Province string `json:"province"`
}

type OPDInput struct {
	Name    string       `json:"name"`
	Address AddressInput `json:"address"`
}

type OrganizerInput struct {
	Name     string       `json:"name"`
	Longname string       `json:"longname"`
	Address  AddressInput `json:"address"`
}

type ParticipantInput struct {
	Name          string   `json:"name"`
	Nip           string   `json:"nip"`
	CurrentJob    string   `json:"current_job"`
	CurrentGrade  string   `json:"current_grade"`
	CurrentPlaces OPDInput `json:"current_places"`
}

type ScheduleInput struct {
	Description string    `json:"description"`
	Start       time.Time `json:"start"`
	Finish      time.Time `json:"finish"`
}

type TrainingInput struct {
	Name         string             `json:"name"`
	Description  string             `json:"description"`
	HeldAt       ScheduleInput      `json:"heldAt"`
	Organizer    OrganizerInput     `json:"organizer"`
	Participants []ParticipantInput `json:"participants"`
}
