// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AsnConnection struct {
	TotalCount int        `json:"totalCount"`
	Edges      []*AsnEdge `json:"edges"`
	PageInfo   PageInfo   `json:"pageInfo"`
}

type AsnEdge struct {
	Node   Asn    `json:"node"`
	Cursor string `json:"cursor"`
}

type AsnInput struct {
	Name          string    `json:"name"`
	Nip           *string   `json:"nip"`
	CurrentJob    *string   `json:"current_job"`
	CurrentGrade  *string   `json:"current_grade"`
	CurrentPlaces *OpdInput `json:"current_places"`
}

type OpdConnection struct {
	TotalCount int        `json:"totalCount"`
	Edges      []*OpdEdge `json:"edges"`
	PageInfo   PageInfo   `json:"pageInfo"`
}

type OpdEdge struct {
	Node   Opd `json:"node"`
	Cursor int `json:"cursor"`
}

type OpdInput struct {
	Name       string  `json:"name"`
	LongName   string  `json:"long_name"`
	RoadNumber *string `json:"road_number"`
	City       string  `json:"city"`
	Province   *string `json:"province"`
}

type OrgInput struct {
	Name       string  `json:"name"`
	LongName   string  `json:"long_name"`
	RoadNumber *string `json:"road_number"`
	City       string  `json:"city"`
	Province   *string `json:"province"`
}

type PageInfo struct {
	StartCursor     *int `json:"startCursor"`
	EndCursor       *int `json:"endCursor"`
	HasPreviousPage bool `json:"hasPreviousPage"`
	HasNextPage     bool `json:"hasNextPage"`
}

type TrxCat struct {
	ID          *int    `json:"id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
}

type TrxCatInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type TrxDetailConnection struct {
	TotalCount *int             `json:"totalCount"`
	Edges      []*TrxDetailEdge `json:"edges"`
	PageInfo   PageInfo         `json:"pageInfo"`
}

type TrxDetailEdge struct {
	Node   TrxDetail `json:"node"`
	Cursor string    `json:"cursor"`
}

type TrxInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type TrxType struct {
	ID          *int    `json:"id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
}

type TrxTypeInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}
